name: zapx
description: >
 Powerful Flutter extensions for navigation, validation, localization.
version: 1.0.4
homepage: https://github.com/saifmalsheref/zapx
repository: https://github.com/saifmalsheref/zapx


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


